runtime: python37
entrypoint: gunicorn -b :$PORT {{cookiecutter.project_name}}.wsgi

env_variables:
  SECRET_KEY: "{{cookiecutter.secret_key}}"
  DB_CONNECTION_NAME: "{{cookiecutter.db_connection_name}}"
  DB_NAME: "{{cookiecutter.db_name}}"
  DB_USER: "{{cookiecutter.db_user}}"
  DB_PASSWORD: "{{cookiecutter.db_password}}"

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto